In [2]:
import numpy as np
import pandas as pd
import re
import nltk


movies = pd.read_csv("movie_data.csv")
movies

Original Title       ID  \
0                   Red One   845781   
1     Venom: The Last Dance   912649   
2      Sonic the Hedgehog 3   939243   
3     Mufasa: The Lion King   762509   
4                   Moana 2  1241982   
...                     ...      ...   
9995                Tomcats    10646   
9996            Airport '77     7227   
9997               Rye Lane  1049638   
9998             胸が鳴るのは君のせい   803279   
9999       Alex Strangelove   511785   

                                            Genres  Adult  \
0                          Action, Fantasy, Comedy  False   
1     Action, Science Fiction, Adventure, Thriller  False   
2          Action, Science Fiction, Comedy, Family  False   
3              Adventure, Family, Drama, Animation  False   
4             Animation, Adventure, Family, Comedy  False   
...                                            ...    ...   
9995                               Comedy, Romance  False   
9996            Action, Adventure, Drama, Thriller  False   
9997                               Comedy, Romance  False   
9998                                Romance, Drama  False   
9999                                 Comedy, Drama  False   

                                               Overview  Rating  \
0     After Santa Claus (codename: Red One) is kidna...    70.2   
1     Eddie and Venom are on the run. Hunted by both...    68.0   
2     Sonic, Knuckles, and Tails reunite against a p...    78.0   
3     Told in flashbacks, Mufasa is an orphaned cub,...    71.0   
4     After receiving an unexpected call from her wa...    69.4   
...                                                 ...     ...   
9995  College buddies chip in and promise that the g...    51.0   
9996  Flight 23 has crashed in the Bermuda Triangle ...    55.9   
9997  Two twenty-somethings, both reeling from bad b...    71.0   
9998  When Tsukasa was a middle school student, she ...    75.0   
9999  Alex Truelove is on a quest to lose his virgin...    65.8   

      Runtime (Seconds)                                             Actors  \
0                  7440  Dwayne Johnson, Chris Evans, Lucy Liu, J.K. Si...   
1                  6540  Tom Hardy, Chiwetel Ejiofor, Juno Temple, Clar...   
2                  6600  Ben Schwartz, Jim Carrey, Keanu Reeves, Idris ...   
3                  7080  Aaron Pierre, Kelvin Harrison Jr., Tiffany Boo...   
4                  6000  Auliʻi Cravalho, Dwayne Johnson, Hualālai Chun...   
...                 ...                                                ...   
9995               5700  Jerry O'Connell, Shannon Elizabeth, Jake Busey...   
9996               6840  Jack Lemmon, Lee Grant, Brenda Vaccaro, Joseph...   
9997               4920  David Jonsson, Vivian Oparah, Poppy Allen-Quar...   
9998               6240  Ukisho Hidaka, Sei Shiraishi, Mizuki Itagaki, ...   
9999               5940  Daniel Doheny, Madeline Weinstein, Antonio Mar...   

                                             Characters              Director  \
0     Callum Drift, Jack O'Malley, Zoe, Nick, Mrs. C...           Jake Kasdan   
1     Eddie Brock / Venom, General Rex Strickland, D...          Kelly Marcel   
2     Sonic (voice), Dr. Robotnik / Gerald Robotnik,...           Jeff Fowler   
3     Mufasa (voice), Taka (voice), Sarabi (voice), ...         Barry Jenkins   
4     Moana (voice), Maui (voice), Moni (voice), Lot...  David G. Derrick Jr.   
...                                                 ...                   ...   
9995  Michael Delaney, Officer Natalie Parker, Kyle ...       Gregory Poirier   
9996  Don Gallagher, Karen Wallace, Eve Clayton, Nic...         Jerry Jameson   
9997                       Dom, Yas, Cass, Nathan, Eric    Raine Allen-Miller   
9998  Arima Hayato, Shinohara Tsukasa, Hasebe Yasuhi...      Hiroto Takahashi   
9999         Alex Truelove, Claire, Elliott, Dell, Josh         Craig Johnson   

     Certification  
0            PG-13  
1            PG-13  
2               PG  


In [3]:
## Process Data
## Clean up overviews
movies['clean_overview'] = movies['Overview'].fillna('')

# Clean up text: Convert to lowercase, remove non-alphanumeric characters, and trim spaces
movies['clean_overview'] = movies['clean_overview'].apply(
    lambda x: re.sub(r'[^a-z0-9]', ' ', x.lower()) if isinstance(x, str) else ''
)
movies['clean_overview'] = movies['clean_overview'].apply(
    lambda x: re.sub(r'\s+', ' ', x).strip()
)

print(movies['clean_overview'].head())

0    after santa claus codename red one is kidnappe...
1    eddie and venom are on the run hunted by both ...
2    sonic knuckles and tails reunite against a pow...
3    told in flashbacks mufasa is an orphaned cub l...
4    after receiving an unexpected call from her wa...
Name: clean_overview, dtype: object


In [4]:
# Tokenize Sentence

movies['clean_overview'] = movies['clean_overview'].apply(
    lambda x: ' '.join(x) if isinstance(x, list) else x
)

# Tokenize sentences
movies['clean_overview'] = movies['clean_overview'].apply(nltk.word_tokenize)
movies

Original Title       ID  \
0                   Red One   845781   
1     Venom: The Last Dance   912649   
2      Sonic the Hedgehog 3   939243   
3     Mufasa: The Lion King   762509   
4                   Moana 2  1241982   
...                     ...      ...   
9995                Tomcats    10646   
9996            Airport '77     7227   
9997               Rye Lane  1049638   
9998             胸が鳴るのは君のせい   803279   
9999       Alex Strangelove   511785   

                                            Genres  Adult  \
0                          Action, Fantasy, Comedy  False   
1     Action, Science Fiction, Adventure, Thriller  False   
2          Action, Science Fiction, Comedy, Family  False   
3              Adventure, Family, Drama, Animation  False   
4             Animation, Adventure, Family, Comedy  False   
...                                            ...    ...   
9995                               Comedy, Romance  False   
9996            Action, Adventure, Drama, Thriller  False   
9997                               Comedy, Romance  False   
9998                                Romance, Drama  False   
9999                                 Comedy, Drama  False   

                                               Overview  Rating  \
0     After Santa Claus (codename: Red One) is kidna...    70.2   
1     Eddie and Venom are on the run. Hunted by both...    68.0   
2     Sonic, Knuckles, and Tails reunite against a p...    78.0   
3     Told in flashbacks, Mufasa is an orphaned cub,...    71.0   
4     After receiving an unexpected call from her wa...    69.4   
...                                                 ...     ...   
9995  College buddies chip in and promise that the g...    51.0   
9996  Flight 23 has crashed in the Bermuda Triangle ...    55.9   
9997  Two twenty-somethings, both reeling from bad b...    71.0   
9998  When Tsukasa was a middle school student, she ...    75.0   
9999  Alex Truelove is on a quest to lose his virgin...    65.8   

      Runtime (Seconds)                                             Actors  \
0                  7440  Dwayne Johnson, Chris Evans, Lucy Liu, J.K. Si...   
1                  6540  Tom Hardy, Chiwetel Ejiofor, Juno Temple, Clar...   
2                  6600  Ben Schwartz, Jim Carrey, Keanu Reeves, Idris ...   
3                  7080  Aaron Pierre, Kelvin Harrison Jr., Tiffany Boo...   
4                  6000  Auliʻi Cravalho, Dwayne Johnson, Hualālai Chun...   
...                 ...                                                ...   
9995               5700  Jerry O'Connell, Shannon Elizabeth, Jake Busey...   
9996               6840  Jack Lemmon, Lee Grant, Brenda Vaccaro, Joseph...   
9997               4920  David Jonsson, Vivian Oparah, Poppy Allen-Quar...   
9998               6240  Ukisho Hidaka, Sei Shiraishi, Mizuki Itagaki, ...   
9999               5940  Daniel Doheny, Madeline Weinstein, Antonio Mar...   

                                             Characters              Director  \
0     Callum Drift, Jack O'Malley, Zoe, Nick, Mrs. C...           Jake Kasdan   
1     Eddie Brock / Venom, General Rex Strickland, D...          Kelly Marcel   
2     Sonic (voice), Dr. Robotnik / Gerald Robotnik,...           Jeff Fowler   
3     Mufasa (voice), Taka (voice), Sarabi (voice), ...         Barry Jenkins   
4     Moana (voice), Maui (voice), Moni (voice), Lot...  David G. Derrick Jr.   
...                                                 ...                   ...   
9995  Michael Delaney, Officer Natalie Parker, Kyle ...       Gregory Poirier   
9996  Don Gallagher, Karen Wallace, Eve Clayton, Nic...         Jerry Jameson   
9997                       Dom, Yas, Cass, Nathan, Eric    Raine Allen-Miller   
9998  Arima Hayato, Shinohara Tsukasa, Hasebe Yasuhi...      Hiroto Takahashi   
9999         Alex Truelove, Claire, Elliott, Dell, Josh         Craig Johnson   

     Certification                                     clean_overview  
0           

In [5]:
# Remove Stop Words

# Ensure no extra appends
stop_words = nltk.corpus.stopwords.words('english')
overview = []

for sentence in movies['clean_overview']:
    temp = []
    for word in sentence:
        if word not in stop_words or len(word) >= 3:
            temp.append(word)
    overview.append(temp)  


In [6]:
movies['clean_overview'] = overview
overview

[['after',
  'santa',
  'claus',
  'codename',
  'red',
  'one',
  'kidnapped',
  'the',
  'north',
  'pole',
  'head',
  'security',
  'must',
  'team',
  'with',
  'the',
  'world',
  'most',
  'infamous',
  'tracker',
  'globe',
  'trotting',
  'action',
  'packed',
  'mission',
  'save',
  'christmas'],
 ['eddie',
  'and',
  'venom',
  'are',
  'the',
  'run',
  'hunted',
  'both',
  'their',
  'worlds',
  'and',
  'with',
  'the',
  'net',
  'closing',
  'the',
  'duo',
  'are',
  'forced',
  'into',
  'devastating',
  'decision',
  'that',
  'will',
  'bring',
  'the',
  'curtains',
  'down',
  'venom',
  'and',
  'eddie',
  'last',
  'dance'],
 ['sonic',
  'knuckles',
  'and',
  'tails',
  'reunite',
  'against',
  'powerful',
  'new',
  'adversary',
  'shadow',
  'mysterious',
  'villain',
  'with',
  'powers',
  'unlike',
  'anything',
  'they',
  'have',
  'faced',
  'before',
  'with',
  'their',
  'abilities',
  'outmatched',
  'every',
  'way',
  'team',
  'sonic',
  'must

In [7]:
movies['Genres'] = movies['Genres'].apply(
    lambda x: [item.strip() for item in x] if isinstance(x, list) else x.split(',') if isinstance(x, str) else []
)

movies['Actors'] = movies['Actors'].apply(
    lambda x: [actor.strip() for actor in x.split(',')[:4]] if isinstance(x, str) else x if isinstance(x, list) else []
)

movies['Director'] = movies['Director'].apply(
    lambda x: [director.strip() for director in x.split(',')] if isinstance(x, str) else x if isinstance(x, list) else []
)

movies


Original Title       ID  \
0                   Red One   845781   
1     Venom: The Last Dance   912649   
2      Sonic the Hedgehog 3   939243   
3     Mufasa: The Lion King   762509   
4                   Moana 2  1241982   
...                     ...      ...   
9995                Tomcats    10646   
9996            Airport '77     7227   
9997               Rye Lane  1049638   
9998             胸が鳴るのは君のせい   803279   
9999       Alex Strangelove   511785   

                                                 Genres  Adult  \
0                           [Action,  Fantasy,  Comedy]  False   
1     [Action,  Science Fiction,  Adventure,  Thriller]  False   
2          [Action,  Science Fiction,  Comedy,  Family]  False   
3              [Adventure,  Family,  Drama,  Animation]  False   
4             [Animation,  Adventure,  Family,  Comedy]  False   
...                                                 ...    ...   
9995                                 [Comedy,  Romance]  False   
9996            [Action,  Adventure,  Drama,  Thriller]  False   
9997                                 [Comedy,  Romance]  False   
9998                                  [Romance,  Drama]  False   
9999                                   [Comedy,  Drama]  False   

                                               Overview  Rating  \
0     After Santa Claus (codename: Red One) is kidna...    70.2   
1     Eddie and Venom are on the run. Hunted by both...    68.0   
2     Sonic, Knuckles, and Tails reunite against a p...    78.0   
3     Told in flashbacks, Mufasa is an orphaned cub,...    71.0   
4     After receiving an unexpected call from her wa...    69.4   
...                                                 ...     ...   
9995  College buddies chip in and promise that the g...    51.0   
9996  Flight 23 has crashed in the Bermuda Triangle ...    55.9   
9997  Two twenty-somethings, both reeling from bad b...    71.0   
9998  When Tsukasa was a middle school student, she ...    75.0   
9999  Alex Truelove is on a quest to lose his virgin...    65.8   

      Runtime (Seconds)                                             Actors  \
0                  7440  [Dwayne Johnson, Chris Evans, Lucy Liu, J.K. S...   
1                  6540  [Tom Hardy, Chiwetel Ejiofor, Juno Temple, Cla...   
2                  6600  [Ben Schwartz, Jim Carrey, Keanu Reeves, Idris...   
3                  7080  [Aaron Pierre, Kelvin Harrison Jr., Tiffany Bo...   
4                  6000  [Auliʻi Cravalho, Dwayne Johnson, Hualālai Chu...   
...                 ...                                                ...   
9995               5700  [Jerry O'Connell, Shannon Elizabeth, Jake Buse...   
9996               6840  [Jack Lemmon, Lee Grant, Brenda Vaccaro, Josep...   
9997               4920  [David Jonsson, Vivian Oparah, Poppy Allen-Qua...   
9998               6240  [Ukisho Hidaka, Sei Shiraishi, Mizuki Itagaki,...   
9999               5940  [Daniel Doheny, Madeline Weinstein, Antonio Ma...   

                                             Characters  \
0     Callum Drift, Jack O'Malley, Zoe, Nick, Mrs. C...   
1     Eddie Brock / Venom, General Rex Strickland, D...   
2     Sonic (voice), Dr. Robotnik / Gerald Robotnik,...   
3     Mufasa (voice), Taka (voice), Sarabi (voice), ...   
4     Moana (voice), Maui (voice), Moni (voice), Lot...   
...                                                 ...   
9995  Michael Delaney, Officer Natalie Parker, Kyle ...   
9996  Don Gallagher, Karen Wallace, Eve Clayton, Nic...   
9997                       Dom, Yas, Cass, Nathan, Eric   
9998  Arima Hayato, Shinohara Tsukasa, Hasebe Yasuhi...   
9999         Alex Truelove, Claire, Elliott, Dell, Josh   

                    Director Certification  \
0              [Jake Kasdan]         PG-13   
1             [Kelly Marcel]         PG-13   
2              [Jeff Fowler]            PG   
3            [Barry Jenkins]            PG   
4     [David G. Derrick Jr.]            PG   
...         

In [8]:
def clean(sentence):
    temp = []
    for word in sentence:
        temp.append(word.lower().replace(' ', ''))
    return temp

In [9]:
movies['Genres'] = [clean(x) for x in movies['Genres']]
movies['Actors'] = [clean(x) for x in movies['Actors']]
movies['Director'] = [clean(x) for x in movies['Director']]
movies

Original Title       ID  \
0                   Red One   845781   
1     Venom: The Last Dance   912649   
2      Sonic the Hedgehog 3   939243   
3     Mufasa: The Lion King   762509   
4                   Moana 2  1241982   
...                     ...      ...   
9995                Tomcats    10646   
9996            Airport '77     7227   
9997               Rye Lane  1049638   
9998             胸が鳴るのは君のせい   803279   
9999       Alex Strangelove   511785   

                                             Genres  Adult  \
0                         [action, fantasy, comedy]  False   
1     [action, sciencefiction, adventure, thriller]  False   
2          [action, sciencefiction, comedy, family]  False   
3             [adventure, family, drama, animation]  False   
4            [animation, adventure, family, comedy]  False   
...                                             ...    ...   
9995                              [comedy, romance]  False   
9996           [action, adventure, drama, thriller]  False   
9997                              [comedy, romance]  False   
9998                               [romance, drama]  False   
9999                                [comedy, drama]  False   

                                               Overview  Rating  \
0     After Santa Claus (codename: Red One) is kidna...    70.2   
1     Eddie and Venom are on the run. Hunted by both...    68.0   
2     Sonic, Knuckles, and Tails reunite against a p...    78.0   
3     Told in flashbacks, Mufasa is an orphaned cub,...    71.0   
4     After receiving an unexpected call from her wa...    69.4   
...                                                 ...     ...   
9995  College buddies chip in and promise that the g...    51.0   
9996  Flight 23 has crashed in the Bermuda Triangle ...    55.9   
9997  Two twenty-somethings, both reeling from bad b...    71.0   
9998  When Tsukasa was a middle school student, she ...    75.0   
9999  Alex Truelove is on a quest to lose his virgin...    65.8   

      Runtime (Seconds)                                             Actors  \
0                  7440  [dwaynejohnson, chrisevans, lucyliu, j.k.simmons]   
1                  6540  [tomhardy, chiwetelejiofor, junotemple, clarkb...   
2                  6600   [benschwartz, jimcarrey, keanureeves, idriselba]   
3                  7080  [aaronpierre, kelvinharrisonjr., tiffanyboone,...   
4                  6000  [auliʻicravalho, dwaynejohnson, hualālaichung,...   
...                 ...                                                ...   
9995               5700  [jerryo'connell, shannonelizabeth, jakebusey, ...   
9996               6840  [jacklemmon, leegrant, brendavaccaro, josephco...   
9997               4920  [davidjonsson, vivianoparah, poppyallen-quarmb...   
9998               6240  [ukishohidaka, seishiraishi, mizukiitagaki, na...   
9999               5940  [danieldoheny, madelineweinstein, antoniomarzi...   

                                             Characters             Director  \
0     Callum Drift, Jack O'Malley, Zoe, Nick, Mrs. C...         [jakekasdan]   
1     Eddie Brock / Venom, General Rex Strickland, D...        [kellymarcel]   
2     Sonic (voice), Dr. Robotnik / Gerald Robotnik,...         [jefffowler]   
3     Mufasa (voice), Taka (voice), Sarabi (voice), ...       [barryjenkins]   
4     Moana (voice), Maui (voice), Moni (voice), Lot...  [davidg.derrickjr.]   
...                                                 ...                  ...   
9995  Michael Delaney, Officer Natalie Parker, Kyle ...     [gregorypoirier]   
9996  Don Gallagher, Karen Wallace, Eve Clayton, Nic...       [jerryjameson]   
9997                       Dom, Yas, Cass, Nathan, Eric  [raineallen-miller]   
9998  Arima Hayato, Shinohara Tsukasa, Hasebe Yasuhi...    [hirototakahashi]   
9999         Alex Truelove, Claire, Elliott, Dell, Josh       [craigjohnson]   

     Certification                                     clean_overview  
0           

In [10]:
# Combining all the data into a single list
columns = ['clean_overview','Genres','Actors','Director']

l = []

for i in range(len(movies)):
    words =''
    for col in columns:
        words += ' '.join(movies[col][i]) + ' '
    l.append(words)
l

['after santa claus codename red one kidnapped the north pole head security must team with the world most infamous tracker globe trotting action packed mission save christmas action fantasy comedy dwaynejohnson chrisevans lucyliu j.k.simmons jakekasdan ',
 'eddie and venom are the run hunted both their worlds and with the net closing the duo are forced into devastating decision that will bring the curtains down venom and eddie last dance action sciencefiction adventure thriller tomhardy chiwetelejiofor junotemple clarkbacko kellymarcel ',
 'sonic knuckles and tails reunite against powerful new adversary shadow mysterious villain with powers unlike anything they have faced before with their abilities outmatched every way team sonic must seek out unlikely alliance hopes stopping shadow and protecting the planet action sciencefiction comedy family benschwartz jimcarrey keanureeves idriselba jefffowler ',
 'told flashbacks mufasa orphaned cub lost and alone until meets sympathetic lion nam

In [11]:
movies['clean_overview'] = l
movies = movies[['Original Title','clean_overview']]
movies.head()

Original Title                                     clean_overview
0                Red One  after santa claus codename red one kidnapped t...
1  Venom: The Last Dance  eddie and venom are the run hunted both their ...
2   Sonic the Hedgehog 3  sonic knuckles and tails reunite against power...
3  Mufasa: The Lion King  told flashbacks mufasa orphaned cub lost and a...
4                Moana 2  after receiving unexpected call from her wayfi...

In [12]:
##  Feature Extraction

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
features = tfidf.fit_transform(movies['clean_overview'])

In [13]:
# Similarity Matrix using cosine similarity
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(features,features)
print(similarity)

[[1.         0.01921062 0.03953509 ... 0.00856931 0.         0.01203546]
 [0.01921062 1.         0.02684518 ... 0.03058611 0.01430265 0.01818551]
 [0.03953509 0.02684518 1.         ... 0.01759677 0.0021778  0.01422896]
 ...
 [0.00856931 0.03058611 0.01759677 ... 1.         0.00592633 0.00719762]
 [0.         0.01430265 0.0021778  ... 0.00592633 1.         0.00568237]
 [0.01203546 0.01818551 0.01422896 ... 0.00719762 0.00568237 1.        ]]


In [14]:
## Movie Recommendation

index = pd.Series(movies['Original Title'])
index.head(5)

0                  Red One
1    Venom: The Last Dance
2     Sonic the Hedgehog 3
3    Mufasa: The Lion King
4                  Moana 2
Name: Original Title, dtype: object

In [15]:
## Recommendation Function

def recommend_movies(title):
    title = title.lower() 
    matching_indices = index[index.str.lower() == title].index  # Match the title in lowercase

    if len(matching_indices) == 0:
        print(f"Movie '{title}' not found in the dataset.")
        return []

    idx = matching_indices[0]
    print(f"Found movie at index {idx}.")

    # Compute similarity scores
    score = pd.Series(similarity[idx]).sort_values(ascending=False)

    # Get top 10 recommended movie indices (excluding the input movie itself)
    top10_indices = score.index[1:11]  # Exclude the first index (the input movie itself)

    # Retrieve movie titles for recommendations
    recommended_movies = []
    for i in top10_indices:
        recommended_movies.append(movies['Original Title'][i])

    return recommended_movies

In [21]:
recommend_movies('red one')


Found movie at index 0.


['The Snowman',
 'Fred Claus',
 'Arthur Christmas',
 'The Christmas Chronicles: Part Two',
 'Santa Claus: The Movie',
 'Saving Santa',
 'Jumanji: The Next Level',
 'The Santa Clause 2',
 'The Santa Clause 3: The Escape Clause',
 'Get Santa']